### ISSUE TITLE
ScrollContainerStyle proptype number should be object

### ISSUE THREAD

**Issue by goldenice** [jrans/react-native-smart-scroll-view#17]
That should be an object; scrollContainerStyle property should be able to receive styles, just like the default value is. The default value of scrollContainerStyle is `styles.flex1`, which is a style, not a number.

I can submit a pull request to fix this if desired?

**Comment by nikhilaravi** [comment]
@goldenice sorry for the late reply! Yes please do submit a pull request. Thanks! :smile:

**Comment by nikhilaravi** [comment]
@goldenice did you manage to fix this?

**Comment by mlabrum** [comment]
@nikhilaravi I've submitted a pull request to fix this :)
