### ISSUE TITLE
this._findScrollWindowHeight is not a function

### ISSUE THREAD

**Issue by MirGhojam** [jrans/react-native-smart-scroll-view#20]
![img_3247](https://cloud.githubusercontent.com/assets/17875337/15008413/f32b3f88-1201-11e6-96c5-2aa0184008c9.PNG)

**Comment by nikhilaravi** [comment]
@MirGhojam so sorry for the delay in getting back to you! did you manage to fix this? If not let us know and we'll take a look!

**Comment by MirGhojam** [comment]
This error automatically disappear that very afternoon. I haven't encountered it since then. Thank u 4 the replay.

**Comment by MirGhojam** [comment]
@nikhilaravi This error automatically disappear that very afternoon. I haven't encountered it since then. Thank u 4 the reply.

**Comment by nikhilaravi** [comment]
@MirGhojam great! Closing this issue!
