### ISSUE TITLE
Refresh control stops working when SmartScrollView is passed as `renderScrollComponent` prop to ListView component

### ISSUE THREAD

**Issue by mayask** [jrans/react-native-smart-scroll-view#21]
See example:

``` javascript
  render() {
    return (
      <ListView
        refreshControl={
          <RefreshControl
            renderScrollComponent={props => <SmartScrollView {...props} />}
            refreshing={this.state.refreshing}
            onRefresh={this._onRefresh.bind(this)}
          />
        }
        ...
      >
      ...
      </ListView>
    );
  }
```

**Comment by nikhilaravi** [comment]
@myaskevich sorry for the late reply! did you manage to figure out why it wasn't working?

**Comment by mayask** [comment]
Hi @nikhilaravi .

No, not yet. I rewrote the app so it didn't require to use `react-native-smart-scroll-view`.

**Comment by nikhilaravi** [comment]
@myaskevich oh okay.

Looking at [this issue](https://github.com/jaysoo/react-native-parallax-scroll-view/issues/20) on a similar component, the suggestion is to use the renderScrollComponent Prop of the listView and not the RefreshControl. 

```
<ListView
  renderScrollComponent={props => (
    <SmartScrollview
      {...props}
      .../>
  }}
 refreshControl={
    <RefreshControl
       refreshing={this.state.refreshing}
       onRefresh={this._onRefresh.bind(this)}
   />}
/>
```

Just in case you ever need to use SmarScrollView again!!!
